CREATE TABLE TF_SOURCE_MAKE_ACTIVE
(
  PENN_ID              VARCHAR2(15 CHAR)        NOT NULL,
  PENNNAME             VARCHAR2(25 CHAR)        NOT NULL,
  ACTIVE               VARCHAR2(1 CHAR)         NOT NULL,
  DOCUMENTATION        VARCHAR2(1000 CHAR)      NOT NULL,
  CREATED_ON           DATE                     NOT NULL,
  CREATED_BY_PENNNAME  VARCHAR2(25 CHAR)        NOT NULL
);
