CREATE OR REPLACE FORCE VIEW TF_PERSON_SOURCE_TEST_V
(
   PENN_ID,
   PENNNAME,
   DESCRIPTION,
   SEARCH_DESCRIPTION,
   NAME,
   EMAIL,
   ACTIVE
)
   BEQUEATH DEFINER
AS
   SELECT PENN_ID,
          PENNNAME,
          DESCRIPTION_PENN AS DESCRIPTION,
          SEARCH_DESCRIPTION_PENN AS SEARCH_DESCRIPTION,
          NAME_PENN AS NAME,
          EMAIL,
          ACTIVE
     FROM TF_PERSON_SOURCE_HELPER_V
  union
   SELECT PENN_ID,
          PENNNAME,
          DESCRIPTION,
          SEARCH_DESCRIPTION,
          NAME,
          EMAIL,
          ACTIVE
     FROM TF_TEST_PERSON
;       
     ;