/* Formatted on 6/7/2015 8:38:58 PM (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW TF_PERSON_SOURCE_V
(
   PENN_ID,
   PENNNAME,
   DESCRIPTION,
   SEARCH_DESCRIPTION,
   NAME,
   EMAIL,
   ACTIVE
)
AS
   SELECT    PENN_ID,
   PENNNAME,
   DESCRIPTION_PENN as DESCRIPTION,
   SEARCH_DESCRIPTION_PENN as SEARCH_DESCRIPTION,
   NAME_PENN as NAME,
   EMAIL,
   ACTIVE
 FROM TF_PERSON_SOURCE_HELPER_V;

COMMENT ON TABLE TF_PERSON_SOURCE_V IS 'person source to lookup and search for subjects in the two factor project for non admin users';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.PENN_ID IS 'numeric penn_id';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.PENNNAME IS 'pennkey of the user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.DESCRIPTION IS 'description to show on screen';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.SEARCH_DESCRIPTION IS 'lower search description to search with';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.NAME IS 'name of user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.EMAIL IS 'email of user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.ACTIVE IS 'T if active, F if not';



GRANT SELECT ON TF_PERSON_SOURCE_V TO TWO_FACTOR_ADMIN WITH GRANT OPTION;
