/* Formatted on 1/6/2017 2:07:22 PM (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW TF_PERSON_SOURCE_V
(
   PENN_ID,
   PENNNAME,
   DESCRIPTION,
   SEARCH_DESCRIPTION,
   NAME,
   EMAIL,
   ACTIVE,
   BIRTH_DATE
)
   BEQUEATH DEFINER
AS
   SELECT PENN_ID,
          PENNNAME,
          DESCRIPTION_PENN AS DESCRIPTION,
          SEARCH_DESCRIPTION_PENN AS SEARCH_DESCRIPTION,
          NAME_PENN AS NAME,
          EMAIL,
          ACTIVE,
          BIRTH_DATE
     FROM TF_PERSON_SOURCE_HELPER_V;

COMMENT ON TABLE TF_PERSON_SOURCE_V IS 'person source to lookup and search for subjects in the two factor project for non admin users';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.PENN_ID IS 'numeric penn_id';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.PENNNAME IS 'pennkey of the user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.DESCRIPTION IS 'description to show on screen';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.SEARCH_DESCRIPTION IS 'lower search description to search with';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.NAME IS 'name of user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.EMAIL IS 'email of user';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.ACTIVE IS 'T if active, F if not';

COMMENT ON COLUMN TF_PERSON_SOURCE_V.BIRTH_DATE IS 'birth date of the user used in optin if it exists for the user';


GRANT SELECT ON TF_PERSON_SOURCE_V TO TWO_FACTOR_ADMIN WITH GRANT OPTION;
